map $host $portal_upstream {
    default                   main:80;
    negarit.local             main:80;
    approval.negarit.local    approval:80;
    agencies.negarit.local    agency:80;
    admin.negarit.local       admin:80;
}

server {
    listen 80 default_server;
    server_name negarit.local approval.negarit.local agencies.negarit.local admin.negarit.local localhost;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/broadcast/ {
        proxy_pass http://broadcast-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://$portal_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
